[package]
name = "lokey-cli"
description = "lokey: a local-only encrypted key/value vault for your terminal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[[bin]]
name = "lokey"
path = "src/main.rs"

[dependencies]
lokey-core.workspace = true
rpassword.workspace = true
zeroize.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[lints]
workspace = true
